package com.example.frontend;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.text.SpannableStringBuilder;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.example.frontend.apiWrappers.ServerRequest;
import com.example.frontend.apiWrappers.UBCGradesRequest;
import com.example.frontend.models.CourseGradesModel;
import com.example.frontend.models.Deserializer;
import com.github.mikephil.charting.charts.BarChart;
import com.github.mikephil.charting.components.XAxis;
import com.github.mikephil.charting.components.YAxis;
import com.github.mikephil.charting.data.BarData;
import com.github.mikephil.charting.data.BarDataSet;
import com.github.mikephil.charting.data.BarEntry;
import com.github.mikephil.charting.data.Entry;
import com.github.mikephil.charting.formatter.IndexAxisValueFormatter;
import com.github.mikephil.charting.highlight.Highlight;
import com.github.mikephil.charting.listener.OnChartValueSelectedListener;
import com.google.android.material.materialswitch.MaterialSwitch;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class CourseSearchActivity extends AppCompatActivity {
    private final String[] availableYearSessions = {"", "2023S", "2022W", "2022S", "2021W", "2021S"};
    private final String BASE_URI = "/api/v3/";
    private final String CAMPUS = "UBCV";
    private final int NUM_SPINNERS = 4;

    private String[] spinnerURIs = {"subjects", "courses", "sections", "grades"};
    private String[] spinnerItems = new String[4];

    private Spinner[] spinners = new Spinner[NUM_SPINNERS];
    private int[] spinnerIds = {R.id.yearSession, R.id.subject, R.id.course, R.id.section};
    private ArrayAdapter<String>[] adapters = new ArrayAdapter[NUM_SPINNERS];

    private TextView courseName;
    private TextView average;
    private TextView stats;
    private TextView teachers;
    private TextView enrolled;
    private CourseGradesModel courseGradesModel;
    private MaterialSwitch favouriteSwitch;
    private BarChart barChart;

    /**
     * Generated by ChatGPT
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_course_search);
        BottomNavMenu.createBottomNavMenu(this, findViewById(R.id.bottom_navigation), R.id.action_home);

        courseName = findViewById(R.id.courseName);
        average = findViewById(R.id.average);
        stats = findViewById(R.id.stats);
        teachers = findViewById(R.id.teachers);
        enrolled = findViewById(R.id.enrolled);
        barChart = findViewById(R.id.barChart);

        favouriteSwitch = findViewById(R.id.favSwitch);
        initializeFavouriteSwitch(favouriteSwitch);

        for (int i=0; i < NUM_SPINNERS; i++) {
            spinners[i] = findViewById(spinnerIds[i]);
            if (i == 0) adapters[i] = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item, availableYearSessions);
            else adapters[i] = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item);
            adapters[i].setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
            spinners[i].setAdapter(adapters[i]);
            final int spinnerIndex = i;
            spinners[i].setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
                @Override
                public void onItemSelected(AdapterView<?> parentView, View selectedItemView, int position, long id) {
                    String selectedItem = adapters[spinnerIndex].getItem(position);
                    if (!selectedItem.equals("")) {
                        updateOtherSpinnersOnChange(selectedItem, spinnerIndex);
                        updateNextSpinnerWithApiData(spinnerIndex);
                    }
                }

                @Override
                public void onNothingSelected(AdapterView<?> parentView) {
                    // Do nothing here
                }
            });
        }
    }

    /**
     * Generated by ChatGPT
     */
    private void updateNextSpinnerWithApiData(int currentSpinnerIndex) {
        if (currentSpinnerIndex < 4) {
            String apiEndpoint = constructEndpoint(currentSpinnerIndex);
            if (currentSpinnerIndex < 3) callUBCGradesJsonArray(currentSpinnerIndex, apiEndpoint);
            else callUBCGradesJsonObject(apiEndpoint);
        }
    }

    /**
     * Generated by ChatGPT
     */
    private void updateSpinnerWithData(JsonArray responseData, int spinnerIndex) {
        if (spinnerIndex < 4) {
            adapters[spinnerIndex].clear();

            adapters[spinnerIndex].add("");
            for (int i = 0; i < responseData.size(); i++) {
                if (spinnerIndex == 1) {
                    adapters[spinnerIndex].add(
                            responseData.get(i).getAsJsonObject().get("subject").getAsString());
                } else if (spinnerIndex == 2) {
                    adapters[spinnerIndex].add(
                            responseData.get(i).getAsJsonObject().get("course").getAsString()
                            + responseData.get(i).getAsJsonObject().get("detail").getAsString());
                } else if (spinnerIndex == 3) {
                    adapters[spinnerIndex].add(responseData.get(i).getAsString());
                }
            }

            adapters[spinnerIndex].notifyDataSetChanged();
        }
    }

    /**
     * Used to clear subsequent drop down menus if user changes a selection
     * Also updates chose values
     * @param spinnerIndex index to indicate which menu user changed
     */
    private void updateOtherSpinnersOnChange(String selectedItem,int spinnerIndex) {
        spinnerItems[spinnerIndex] = selectedItem;
        for (int i = spinnerIndex + 1; i < NUM_SPINNERS; i++) {
            spinnerItems[i] = "";
            adapters[i].clear();
        }
    }

    /**
     * Constructs endpoint to call depending on which dropdown menu is clicked and
     * which options were previously chosen
     * @param spinnerIndex current dropdown menu
     */
    private String constructEndpoint(int spinnerIndex) {
        StringBuilder endpoint = new StringBuilder(BASE_URI);
        endpoint.append(spinnerURIs[spinnerIndex]);
        endpoint.append("/" + CAMPUS);
        for (int i = 0; i < spinnerIndex+1; i++) {
            endpoint.append("/" + spinnerItems[i]);
        }
        return endpoint.toString();
    }

    private void callUBCGradesJsonArray(int currentSpinnerIndex, String apiEndpoint) {
        UBCGradesRequest ubcGradesRequest = new UBCGradesRequest();
        UBCGradesRequest.ApiRequestListener apiRequestListener = new UBCGradesRequest.ApiRequestListener<JsonArray>() {
            @Override
            public void onApiRequestComplete(JsonArray response) {
                updateSpinnerWithData(response, currentSpinnerIndex + 1);
            }

            @Override
            public void onApiRequestError(String error) {
                Log.d(UBCGradesRequest.RequestTag, "Failure");
                Log.d(UBCGradesRequest.RequestTag, error);
            }
        };
        ubcGradesRequest.makeGetRequestForJsonArray(apiEndpoint, apiRequestListener);
    }

    private void callUBCGradesJsonObject(String apiEndpoint) {
        UBCGradesRequest ubcGradesRequest = new UBCGradesRequest();
        UBCGradesRequest.ApiRequestListener apiRequestListener = new UBCGradesRequest.ApiRequestListener<JsonObject>() {
            @Override
            public void onApiRequestComplete(JsonObject response) {
                Log.d(UBCGradesRequest.RequestTag, "Course grade request success");
                Deserializer deserializer = new Deserializer();
                courseGradesModel = deserializer.courseGradesModelDeserialize(response);
                favouriteSwitch.setChecked(isCourseFavourited());
                favouriteSwitch.setVisibility(View.VISIBLE);

                displaySearchResults(courseGradesModel);
                displayGraph(courseGradesModel.getGrades());
            }
            @Override
            public void onApiRequestError(String error) {
                Log.d(UBCGradesRequest.RequestTag, "Failure");
                Log.d(UBCGradesRequest.RequestTag, error);
            }
        };
        try {
            ubcGradesRequest.makeGetRequestForJsonObject(apiEndpoint, apiRequestListener);
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    private void displaySearchResults(CourseGradesModel data) {
        courseName.setText(String.format("%s %s%s %s %s %s",
                data.getCampus(), data.getYear(), data.getSession(),
                data.getSubject(), data.getCourse(), data.getSection()));
        average.setText(String.format("Average: %s", data.getAverage()));
        stats.setText(String.format("Median: %s, High: %s, Low: %s",
                data.getMedian(), data.getHigh(), data.getLow()));
        teachers.setText(String.format("Teaching Team: %s",
                data.getEducators()));
        enrolled.setText(String.format("Number of students enrolled: %s",
                data.getReported()));
    }

    private void displayGraph(Map<String, Integer> data) {
        ArrayList<BarEntry> entries = new ArrayList<>();
        ArrayList<String> xAxisLabels = new ArrayList<>();
        int index = 1;
        int val = 0;
        for (Map.Entry<String, Integer> entry : data.entrySet()) {
            xAxisLabels.add(entry.getKey());
            entries.add(new BarEntry(index, entry.getValue()));
            val = entry.getValue();
            index++;
        }

        entries.remove(entries.size()-1);
        entries.add(0, new BarEntry(0, val));
        xAxisLabels.add(0, xAxisLabels.remove(xAxisLabels.size()-1));
        BarDataSet dataSet = new BarDataSet(entries, "Values");
        dataSet.setColor(Color.BLUE);
        BarData barData = new BarData(dataSet);

        barChart.getLegend().setEnabled(false);
        barChart.getDescription().setEnabled(false);
        YAxis rightYAxis = barChart.getAxisRight();
        rightYAxis.setEnabled(false);

        YAxis yAxis = barChart.getAxisLeft();
        yAxis.setDrawGridLines(false);

        XAxis xAxis = barChart.getXAxis();
        xAxis.setDrawGridLines(false);
        xAxis.setPosition(XAxis.XAxisPosition.BOTTOM);
        xAxis.setTextSize(8f);
        dataSet.setValueTextSize(0f);
        xAxis.setValueFormatter(new IndexAxisValueFormatter(xAxisLabels));

        barChart.setOnChartValueSelectedListener(new OnChartValueSelectedListener() {
            @Override
            public void onValueSelected(Entry e, Highlight h) {
                dataSet.setValueTextSize(12f);
                barChart.invalidate();
            }
            @Override
            public void onNothingSelected() {
                dataSet.setValueTextSize(0f);
            }
        });
        barChart.setData(barData);
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                barChart.invalidate();
            }
        });
    }

    private void initializeFavouriteSwitch(MaterialSwitch materialSwitch) {
        materialSwitch.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (courseGradesModel == null) {
                    Toast.makeText(CourseSearchActivity.this, "Please choose a course", Toast.LENGTH_SHORT).show();
                } else {
                    String courseId = String.format("%s %s", courseGradesModel.getSubject(), courseGradesModel.getCourse());
                    addFavouriteCourse(courseId);
                }
            }
        });
        materialSwitch.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                String courseId = String.format("%s %s", courseGradesModel.getSubject(), courseGradesModel.getCourse());
                if (isChecked) {
                    addFavouriteCourse(courseId);
                } else {
                    removeCourse(courseId);
                }
            }
        });
    }

    private void addFavouriteCourse(String courseId) {
        SharedPreferences sharedPreferences = getSharedPreferences("GoogleAccountInfo", MODE_PRIVATE);
        String userId = sharedPreferences.getString("userId", null);
        ServerRequest serverRequest = new ServerRequest(userId);
        JsonObject body = new JsonObject();
        body.addProperty("courseId", courseId);

        ServerRequest.ApiRequestListener apiRequestListener = new ServerRequest.ApiRequestListener() {
            @Override
            public void onApiRequestComplete(JsonElement response) {
                Toast.makeText(CourseSearchActivity.this, courseId + " favourited", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onApiRequestError(String error) {
                Log.d(ServerRequest.RequestTag, "Failure");
                Log.d(ServerRequest.RequestTag, error);
            }
        };

        try {
            serverRequest.makePutRequest("/users/favourite", body, apiRequestListener);
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    private void removeCourse(String courseId) {
        SharedPreferences sharedPreferences = getSharedPreferences("GoogleAccountInfo", MODE_PRIVATE);
        String userId = sharedPreferences.getString("userId", null);
        ServerRequest serverRequest = new ServerRequest(userId);

        ServerRequest.ApiRequestListener apiRequestListener = new ServerRequest.ApiRequestListener() {
            @Override
            public void onApiRequestComplete(JsonElement response) {
                Toast.makeText(CourseSearchActivity.this, courseId + " unfavourited", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onApiRequestError(String error) {
                Log.d(ServerRequest.RequestTag, "Failure");
                Log.d(ServerRequest.RequestTag, error);
            }
        };

        try {
            serverRequest.makeDeleteRequest("/users/favourite/" + courseId, apiRequestListener);
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    private boolean isCourseFavourited() {
        SharedPreferences sharedPreferences = getSharedPreferences("GoogleAccountInfo", MODE_PRIVATE);
        String userId = sharedPreferences.getString("userId", null);
        Set<String> userCourses = getUserCourses(userId);
        String courseId = String.format("%s %s", courseGradesModel.getSubject(), courseGradesModel.getCourse());
        return userCourses.contains(courseId);
    }

    private Set<String> getUserCourses(String userId) {
        ServerRequest serverRequest = new ServerRequest(userId);
        Set<String> userCourses = new HashSet<>();
        ServerRequest.ApiRequestListener apiRequestListener = new ServerRequest.ApiRequestListener() {
            @Override
            public void onApiRequestComplete(JsonElement response) {
                for (JsonElement course : response.getAsJsonArray()) {
                    userCourses.add(course.getAsString());
                }
            }

            @Override
            public void onApiRequestError(String error) {
                Log.d(ServerRequest.RequestTag, "Failure");
                Log.d(ServerRequest.RequestTag, error);
            }
        };

        try {
            serverRequest.makeGetRequest("/users/favourite", apiRequestListener);
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
        return userCourses;
    }
}