name: Running Backend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install modules
      run: cd backend && npm install
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "./backend/src/controllers/cpen-321-ubc-course-connect-firebase-adminsdk-u9hn2-d990795c7e.json"
        json: ${{ secrets.FIREBASE_SECRETS_JSON }}
    - name: run tests
      run: cd backend && npm test
